[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
[window]
opacity = 0.5
padding = { x = 5, y = 5 } 
[font]
builtin_box_drawing = false
size = 13.0
offset = {x = 1, y = 1}
normal = { family = "JetBrainsMono Nerd Font Propo", style = "SemiBold" }

