[background]
path = "/etc/greetd/background.png"
fit = "Fill"
[commands]
reboot = ["loginctl", "reboot"]
poweroff = ["loginctl", "poweroff"]
[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Adwaita"

# Whether to blink the cursor
cursor_blink = true

# Font name and size
font_name = "Maple Mono Medium 16"

# Icon theme name
icon_theme_name = "Adwaita"

# GTK theme name
theme_name = "Adwaita"


