backend = "wal"
palette = "dark16"
checkcontrast = true
[templates]
kitty.template = "kitty.conf"
kitty.target = "~/.config/kitty/colors.conf"
waybar.template = "waybar.css"
waybar.target = "~/.config/waybar/colors.css"
wofi.template = "waybar.css"
wofi.target = "~/.config/wofi/colors.css"
wlogout.template = "waybar.css"
wlogout.target = "~/.config/wlogout/colors.css"
