[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
[window]
opacity = 0.5
padding = { x = 5, y = 5 }
[font]
builtin_box_drawing = false
size = 12.0
offset = { x = 0, y = 0 }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
