[colors.primary]
background = "#2a121a"
foreground = "#c9c3c5"

[colors.cursor]
text = "#2a121a"
cursor = "#c9c3c5"

[colors.vi_mode_cursor]
text = "#2a121a"
cursor = "#c9c3c5"

[colors.search.matches]
foreground = "#2a121a"
background = "#c9c3c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#766169"
background = "#9e9497"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#2a121a"
red = "#7e2d33"
green = "#6f3639"
yellow = "#843938"
blue = "#9a3c36"
magenta = "#a54f3c"
cyan = "#b1734b"
white = "#9e9497"

[colors.bright]
black = "#766169"
red = "#A93C44"
green = "#95494D"
yellow = "#B04C4B"
blue = "#CE5049"
magenta = "#DD6A50"
cyan = "#ED9A64"
white = "#c9c3c5"

[colors.dim]
black = "#c9c3c5"
red = "#A93C44"
green = "#DD6A50"
yellow = "#B04C4B"
blue = "#CE5049"
magenta = "#95494D"
cyan = "#ED9A64"
white = "#766169"

