[helpers]

[default]
depends = []

[default.files]

# Rcs/profile

"rc/bashrc" = "~/.bashrc"
"rc/profile" = "~/.profile"
"rc/zshrc" = "~/.zshrc"

# Decoration

"decor/fastfetch" = "~/.config/fastfetch"
"decor/starship.toml" = "~/.config/starship.toml"
"wallpaper" = { target = "~/.config/niri/wallpaper", type = "symbolic" }
"decor/wallust" = { target = "~/.config/wallust", type = "symbolic" }
"decor/waybar" = "~/.config/waybar"
"decor/wlogout" = "~/.config/wlogout"
"decor/wlogout/icons" = "~/.config/wlogout/icons"

# Functional Utilities

"utils/alacritty" = "~/.config/alacritty"
"utils/kanata" = "~/.config/kanata"
"utils/kitty" = "~/.config/kitty"
"utils/lf" = "~/.config/lf"
"utils/makepkg.conf" = "~/makepkg.conf"
"utils/tmux.conf" = "~/.tmux.conf"
"utils/nvim" = "~/.config/nvim"
"utils/paru" = "~/.config/paru"
"utils/wofi" = "~/.config/wofi"
"utils/helix" = "~/.config/helix"
"utils/greetd" = { target = "/etc/greetd", owner = "root", type = "template" }
"utils/nushell" = "~/.config/nushell"
"utils/niri" = "~/.config/niri"
"utils/swaylock" = "~/.swaylock/config"
"utils/waypaper/style.css" = "~/.config/waypaper/style.css"
"scripts" = "~/.scripts"
[default.variables]
font = "Maple Mono"
fsize = 13
lfsize = 20
opacity = 1
terminal = 'kitty'
[settings]
default_target_type = "automatic"
