[helpers]

[default]
depends = []

[default.files]

# Rcs/profile

"rc/bashrc" = "~/.bashrc"
"rc/profile" = "~/.profile"
"rc/zshrc" = "~/.zshrc"

# Decoration

# I Had a Hrd time placing hypr but i Decided its more decoration. If you want utility use Sway.

"decor/fastfetch" = "~/.config/fastfetch"
"decor/hypr" = "~/.config/hypr"
"decor/starship.toml" = "~/.config/starship.toml"
"decor/wal" = "~/.config/wal"
"wallpaper" = "~/.config/hypr/wallpaper"
"decor/wallust" = "~/.config/wallust"
"decor/waybar" = "~/.config/waybar"
"decor/wlogout" = "~/.config/wlogout"
"decor/wlogout/icons" = "config/wlogout/icons"

# Functional Utilities

"utils/alacritty" = "~/.config/alacritty"
"utils/kanata" = "~/.config/kanata"
"utils/kitty" = "~/.config/kitty"
"utils/lf" = "~/.config/lf"
"utils/makepkg.conf" = "~/makepkg.conf"
"utils/tmux.conf" = "~/.tmux.conf"
"utils/nvim" = "~/.config/nvim"
"utils/paru" = "~/.config/paru"
"utils/wofi" = "~/.config/wofi"
"utils/greetd" = "/etc/greetd"
"utils/nushell" = "~/.config/nushell"

# Services

".service" = "~/.service"

[default.variables]
font = "Maple Mono"
fsize = 13
lfsize = 20
terminal = 'kitty'
[settings]
default_target_type = "automatic"
