[helpers]

[default]
depends = []

[default.files]

# Rcs/profile

"rc/bashrc" = { target = "~/.bashrc", type = "symbolic" }
"rc/profile" = { target = "~/.profile", type = "symbolic" }
"rc/zshrc" = { target = "~/.zshrc", type = "symbolic" }

# Decoration

# I Had a Hrd time placing hypr but i Decided its more decoration. If you want utility use Sway.

"decor/fastfetch" = { target = "~/.config/fastfetch", type = "symbolic" }
"decor/hypr" = "~/.config/hypr"
"decor/starship.toml" = "~/.config/starship.toml"
"decor/wal" = { target = "~/.config/wal", type = "symbolic" }
"wallpaper" = { target = "~/.config/hypr/wallpaper", type = "symbolic" }
"decor/wallust" = { target = "~/.config/wallust", type = "symbolic" }
"decor/waybar" = "~/.config/waybar"
"decor/wlogout" = "~/.config/wlogout"
"decor/wlogout/icons" = { target = "~/.config/wlogout/icons", type = "symbolic" }

# Functional Utilities

"utils/alacritty" = "~/.config/alacritty"
"utils/kanata" = { target = "~/.config/kanata", type = "symbolic" }
"utils/kitty" = "~/.config/kitty"
"utils/lf" = { target = "~/.config/lf", type = "symbolic" }
"utils/makepkg.conf" = { target = "~/makepkg.conf", type = "symbolic" }
"utils/tmux.conf" = { target = "~/.tmux.conf", type = "symbolic" }
"utils/nvim" = { target = "~/.config/nvim", type = "symbolic" }
"utils/paru" = { target = "~/.config/paru", type = "symbolic" }
"utils/wofi" = "~/.config/wofi"
"utils/greetd" = { target = "/etc/greetd", owner = "root", type = "template" }
"utils/nushell" = { target = "~/.config/nushell", type = "symbolic" }

# Services

".service" = "~/.service"

[default.variables]
font = "Maple Mono"
fsize = 13
lfsize = 20
terminal = 'kitty'
[settings]
default_target_type = "automatic"
