[helpers]

[default]
depends = []

[default.files]
"rc/zshrc" = { target = "~/.zshrc", type = "symbolic" }
"rc/bashrc" = { target = "~/.bashrc", type = "symbolic" }
"decor/hypr" = { target = "~/.config/hypr", type = "symbolic" }
"decor/waybar" = { target = "~/.config/waybar", type = "symbolic" }
"utils/nvim" = { target = "~/.config/nvim", type = "symbolic" }
"utils/wofi" = { target = "~/.config/wofi", type = "symbolic" }
"utils/kitty" = { target = "~/.config/kitty", type = "symbolic"  }
"decor/wlogout" = { target = "~/.config/wlogout",  type = "symbolic" }
"utils/lf" = { target = "~/.config/lf" , type = "symbolic" }
"decor/starship.toml" = "~/.config/starship.toml"
"rc/profile" = { target = "~/.profile", type="symbolic" }
"utils/alacritty" = { target = "~/.config/alacritty", type="symbolic" }
"decor/wal" = { target = "~/.config/wal", type="symbolic" }
"decor/wallust" = { target = "~/.config/wallust", type="symbolic" }
"utils/kanata" = { target = "~/.config/kanata", type="symbolic" }
[default.variables]

[settings]
default_target_type = "automatic"
